import Vue from 'vue'
import { Checkbox, Dialog, Search, Swipe, SwipeItem, Grid, GridItem, Button, Rate, Tabbar, TabbarItem, NavBar, Field, Cell, Toast, Icon, ActionSheet } from 'vant'

Vue.use(Dialog)
Vue.use(Checkbox)
Vue.use(ActionSheet)
Vue.use(Icon)
Vue.use(GridItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(NavBar)
Vue.use(Cell)
Vue.use(Field)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Button)
Vue.use(Rate)
Vue.use(Toast)
